### ISSUE TITLE
(SAM-3) Нарисовать макет/flow приложения

### ISSUE THREAD

**Issue by c0dedbear** [FocusStartSpb/PhotoTune#4]

**Comment by c0dedbear** [comment]
Ссылка на прототип. https://marvelapp.com/4a3062b
Постарался обозначить флоу с основными переходами.

**Comment by c0dedbear** [comment]
@svshkv , @anna-belousova иконки, отступы и прочие мелочи могут отличаться это не суть.

**Comment by MisnikovRoman** [comment]
> Ссылка на прототип. https://marvelapp.com/4a3062b
> Постарался обозначить флоу с основными переходами.

@c0dedbear, мне понравился дизайн, если получится все реализовать как в дизайне, будет круто 👍🏻
